name: tests

on:
  - push
  - pull_request

jobs:
  bootstrap-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Bootstrap Tests
      run: python bootstrap/test.py

  mirth-typecheck:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Mirth Typecheck
      run: python bootstrap/mirth.py --typecheck src

  mirth-golden-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Mirth Golden Tests
      run: PYTHONHASHSEED=0 python bootstrap/mirth.py src mtest

